

	
	<nav class="navbar nav-pills-secondary nav bg-success">

  <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl()->getUrl('admin','grid'); ?>">ADMIN</a>
  </li>
  <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl()->getUrl('product','grid'); ?>">PRODUCT</a>
  </li>
 <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl()->getUrl('category','grid'); ?>">CATEGORY</a>
  </li>
  <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl()->getUrl('customer','grid'); ?>">CUSTOMER</a>
  </li>
   <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl()->getUrl('vendor','grid'); ?>">VENDOR</a>
  </li>
  <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl()->getUrl('salesman','grid'); ?>">SALESMAN</a>
  </li>
  <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl()->getUrl('shipping','grid'); ?>">SHIPPING METHOD</a>
  </li>
  <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl()->getUrl('payment','grid'); ?>">PAYMENT METHOD</a>
  </li> <li class="nav">
    <a class="nav-link active link-dark"  href="<?php echo $this->getUrl()->getUrl('eav_attribute','grid'); ?>">EAV</a>
  </li>


