<?php
// echo "<pre>";
$data = $this->product;
// print_r($data);
// $product = $data->getData();
// print_r($data);
?>
		<form action="<?php echo $this->getUrl()->getUrl('product','save');?>" method="POST">
			<table width="20%">
				<tr>
					<td><h3> Product</h3></td>
					<td><button class="btn btn-primary">SAVE</button></td>
				</tr>
			</table>
			<table>
				<tr>
					<td>ProductId :</td>
					<td><input type="number" name="product[product_id]" value="<?php echo $data->product_id;?>"></td>
				</tr>
				<tr>
					<td>NAME :</td>
					<td><input type="text" name="product[name]" value="<?php echo $data->name;?>"></td>
				</tr>
				<tr>
					<td>SKU :</td>
					<td><input style="width:100%" type="text" name="product[sku]" value="<?php echo $data->sku;?>"></td>
				</tr>
				<tr>
					<td>Cost :</td>
					<td><input type="text" name="product[cost]" value="<?php echo $data->cost;?>"></td>
				</tr>
				<tr>
					<td>Price :</td>
					<td><input type="text" name="product[price]" value="<?php echo $data->price;?>"></td>
				</tr>
				<tr>
					<td>Quantity :</td>
					<td><input type="text" name="product[quantity]" value="<?php echo $data->quantity;?>"></td>
				</tr>
				<tr>
					<td>Description :</td>
					<td><input type="text" name="product[description]" value="<?php echo $data->description;?>"></td>
				</tr>
				<tr>
					<td> Status</td>
					<td> <select name="product[status]" >
						<?php foreach ($product->getResource()->getStatusOptions() as $key => $value): ?>
						<option value="<?php echo $key ?>"><?php echo $value ?></option>
						<?php endforeach; ?>
						
					</select> </td>
				</tr>
				<tr>
					<td>Color :</td>
					<td><input type="text" name="product[color]" value="<?php echo $data->color;?>"></td>
				</tr>
				<tr>
					<td>Material :</td>
					<td><input type="text" name="product[material]" value="<?php echo $data->material;?>"></td>
				</tr>
			</table>
		</form>
