<?php
$products = $this->getCollection();
?>
		<div class="container-fluid">
			<div class="row">
				<div class="col-10">
					<h3>PRODUCT</h3>
				</div>
				<div class="col-2">
					<div class="btn btn-light link-success"><a href="<?php echo $this->getUrl()->getUrl('product','add'); ?>">Add Product</a></div>
				</div>
			</div>
		</div>
		<table class="table table-hover table-bordered w-100">
			<thead class="thead-light">
			<tr>
				<th>ProductId</th>
				<th>NAME</th>
				<th>SKU </th>
				<th>Cost</th>
				<th>Price</th>
				<th>Quantity</th>
				<th>Description</th>
				<th>Status</th>
				<th>Color</th>
				<th>Material</th>
				<th>CreatedAt</th>
				<th>UpdatedAt</th>
				<th>Edit</th>
				<th>Delete</th>
				<th>Images</th>
				
			</tr>
	</thead>

			<?php foreach ($products->getData() as $row):  ?>
			<tr>
				<td><?php echo $row->product_id;?></td>
				<td><?php echo $row->name;?></td>
				<td><?php echo $row->sku;?></td>
				<td><?php echo $row->cost;?></td>
				<td><?php echo $row->price;?></td>
				<td><?php echo $row->quantity;?></td>
				<td><?php echo $row->description;?></td>
				<td><?php echo $row->getStatusText();?></td>
				<td><?php echo $row->color;?></td>
				<td><?php echo $row->material;?></td>
				<td><?php echo $row->created_at;?></td>
				<td><?php echo $row->updated_at;?></td>
				<td><a href="<?php echo $this->getUrl()->getUrl('product','edit',
				['product_id'=>$row->product_id]);?>">Edit</a></td>
				<td><a href="<?php echo $this->getUrl()->getUrl('product','delete',
				['product_id'=>$row->product_id]);?>">Delete</a></td>
				<td><a href="<?php echo $this->getUrl()->getUrl('product_media','grid',
				['product_id'=>$row->product_id]);?>">Image</a></td>
				
			</tr>
			<?php endforeach; ?>
		</table>
	</form>
