<?php
$result = $this->address;
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> Vendor Address Grid</title>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
	<?php
		require 'View\html\header.phtml';
		?>
<table class="table table-bordered w-100">
	<tr>
		<th>Address_id</th>
		<th>Address</th>
		<th>City</th>
		<th>State</th>
		<th>Country</th>
		<th>Zip_code</th>
		<th>Vendor_id</th>

	</tr>
		
		 
	<tr>
		<td><?php echo $result->address_id;?></td>
		<td><?php echo $result->address;?></td>
		<td><?php echo $result->city;?></td>
		<td><?php echo $result->state;?></td>
		<td><?php echo $result->country;?></td>
		<td><?php echo $result->zipcode;?></td>
		<td><?php echo $result->vendor_id;?></td>
		
	</tr>
</table>
</body>
</html>