<?php
$data = $this->getCollection();
	?>

	<div class="row">
		<div class="col-9">
			<h3>Admin</h3>
		</div>
		<div class="col-3">

			<div class="btn btn-info link-secondary"><a href="<?php echo $this->getUrl()->getUrl('admin','add'); ?>">Add Admin</a></div>
	</div>

	<table class="table table-hover table-bordered flx ">
			<thead class="thead-light">
		<tr>
			<th>AdminId</th>		
			<th>email</th>		
			<th>status</th>		
			<th>Created At</th>	
			<th>Updated At</th>	
			<th>Edit</th>	
			<th>Delete</th>	
		</tr>
	</thead>

		<?php foreach ($data->getData() as $admin):  ?>
			<tr>
				<td><?php echo $admin->admin_id;?></td>
				<td><?php echo $admin->email;?></td>
				<td><?php echo $admin->getStatusText();?></td>
				<td><?php echo $admin->create_at;?></td>
				<td><?php echo $admin->update_at;?></td>
				<td><a href="<?php echo $this->getUrl()->getUrl('admin','edit',
				['admin_id'=>$admin->admin_id]);?>">Edit</a></td>
				<td><a href="<?php echo $this->getUrl()->getUrl('admin','delete',
				['admin_id'=>$admin->admin_id]);?>">Delete</a></td>
				
			</tr>
			<?php endforeach; ?>	
	</table>

