<?php
$attribute = $this->attribute;

// echo "<pre>";
// print_r($attribute); die();

?>
 <div class="content-main">
        <form action="<?php echo $this->getUrl()->getUrl('eav_attribute','save');?>" method="POST">
        <table>
            <tr>
                <td>
                    <h1>Save Attribute</h1>
                </td>
                <td class="sub-head">
                    <button type="submit" >Save</button>
                    
                </td>
            </tr>
        </table>
        <table border = "2px" style = "border-collapse : collapse;">
           
            <tr>
                <td>Attribute_id</td>
                <td><?php echo $attribute->attribute_id;?></td>
            </tr>
            <tr>
                <td>Entity_Type_ID: </td>
                <td><input type="text" name="attribute[entity_type_id]"  value="<?php echo $attribute->entity_type_id;?>"></td>
            </tr>
            <tr>
                <td>Code </td>
                <td><input type="text" name="attribute[code]" value="<?php echo $attribute->code;?>"></td>
            </tr>
            <tr>
                <td>BAckend Type </td>
                <td><input type="text" name="attribute[backend_type]"  value="<?php echo $attribute->backend_type;?>"></td>
            </tr>
            <tr>
                <td>name </td>
                <td><input type="text" name="attribute[name]" value="<?php echo $attribute->name;?>"></td>
            </tr>
            <tr>
                <td>Status: </td>
                <td>
                    <select name="attribute[status]" >
                        <?php foreach ($attribute->getResource()->getStatusOptions() as $key => $value): ?>
                            <?php $selected = ($key == $attribute->getStatus()) ? 'selected':'' ?>
                            <option <?php echo $selected; ?>><?php echo $value ?></option>
                            <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td>backendModel: </td>
                <td><textarea name="attribute[backend_model]"cols="30" rows="10" ><?php echo $attribute->backend_model;?></textarea></td>
            </tr>
            
            <tr>
                <td>inputtype </td>
                <td><input type="text" name="attribute[input_type]" value="<?php echo $attribute->input_type;?>"> </td>
            </tr>
            

            
        </table>
        
            
        </form>
    </div>
       