<?php
$result = $this->address;
print_r($result);
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> Customer Address Grid</title>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
	<?php
		require 'View\html\header.phtml';
		?> 
<table class="table table-bordered w-100">
	<tr>
		<th>Address_id</th>
		<th>Address</th>
		<th>City</th>
		<th>State</th>
		<th>Country</th>
		<th>Zip_code</th>
		<th> customer_id</th>

	</tr>
		
	<tr>
			<td><?php echo $result->address_id?> </td>
			<td><?php echo $result->address;?></td>
			<td><?php echo $result->city;?></td>
			<td><?php echo $result->state;?></td>
			<td><?php echo $result->country;?></td>
			<td><?php echo $result->zip_code;?></td>
			<td><?php echo $result->customer_id;?></td>
		
		 
	</tr>
</table>
</body>
</html>