<?php
$category = $this->category;
$categoriesData = $this->categoriesData;
?>
<!DOCTYPE html>
<html>
  <head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>edit product</title>
		<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	</head>
  <body>
    <?php
		require 'View\html\header.phtml';
		?>
        <form action="<?php echo $this->getUrl()->getUrl('category','save');?>" method="POST">
    <table class="table w-20">
      <tr>
        <h3> category<h3>
        <button class="btn btn-primary"> save</button>
        
      </tr>
      
    </table>
      </tr>
	<table class="table table-bordered">
      <form action="insert_category.php" method="GET">
        <tr> <th> PARENT CATEGORY</th>
          <td><select name="category[parent_id]" >
            <option value='1' >select</option>
    <?php foreach ($categoriesData as $singleCategory): ?>

    <option value="<?php echo $singleCategory->category_id;?>" 
    <?php if ($category->parent_id == $singleCategory->category_id)
          { echo "selected";}?> >
      <?php echo $singleCategory->getPathName();?>
    </option>
            <?php endforeach; ?>
          </select> </td></tr>
          
          <tr>
            <th> NAME</th>
            <td><input type="text" name="category[name]" value="<?php echo $category->name ?>"></td>
          </tr>
          <tr>
            <th> STATUS</th>
            <td> <select name="category[status]" >
              <?php foreach ($category->getTable()->getStatusOptions() as $key => $value): ?>
            <option value="<?php echo $key ?>"><?php echo $value ?></option>
            <?php endforeach; ?>
              
            </select> </td>
          </tr>
          <tr>
            <th> DESCRIPTION</th>
            <td><input type="text" name="category[description]" value="<?php echo $category->description ?>"></td>
          </tr>
        </form>
        
      </table>
    </body>
  </html>