<?php
$result=$this->category;
// print_r($result);
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> Category_grid</title>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
		
	</head>
	<body>
		<?php
		require 'View\html\header.phtml';
		?>
		<div class="row">
	 	<div class="col-10">
	 		<h3>CATEGORY</h3>
	 	</div>
	 	<div class="col-2">
		 <div class="btn btn-light"><a href="<?php echo $this->getUrl()->getUrl('category','add'); ?>">ADD CATEGORY
		 </a></div> 
	 	</div>
	</div>
		<table class="table table-bordered w-100">
			
			<tr>
				<th>CategoryId</th>
				<th>NAME</th>
				<th>PATH</th>
				<th>Status</th>
				<th>Description</th>
				<th>CreatedAt</th>
				<th>UpdatedAt</th>
				<th>Edit</th>
				<th>Delete</th>
				
			</tr>

			<?php foreach ($result as $row):  ?>
			<tr>
				<td><?php  echo $row->category_id;?> </td>
				<td><?php echo $row->name;?></td>
				<td><?php echo  $row->getPathName(); ?></td>
				<td><?php echo $row->getstatustext();?></td>
				<td><?php echo $row->description;?></td>
				<td><?php echo $row->created_at;?></td>
				<td><?php echo $row->updated_at;?></td>
				<td><a href="<?php echo $this->getUrl()->getUrl('category','edit',
				['category_id'=>$row->category_id]);?>">Edit</a></td>
				<td><a href="<?php echo $this->getUrl()->getUrl('category','delete',['category_id'=>$row->category_id]);?>">Delete</a></td>
				
			</tr>
			<?php endforeach; ?>
		</table>
	</body>
</html>