  <?php
    $result=$this->salesman;
  ?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> salesman_grid</title>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>

	 <?php
		require 'View\html\header.phtml';
		?> 
	 <div class="row">
	 	<div class="col-10">
	 		<h3>SALESMAN</h3>
	 	</div>
	 	<div class="col-2">
	 		
		 <div class="btn btn-light"><a href="<?php echo $this->getUrl()->getUrl('salesman','add'); ?>">ADD SALESMAN
		</a></div> 
	 	</div>
	 </div>
	<table class="table table-bordered ">
		
		<tr>
			<th>SalesmanId</th>
			<th>FirstName</th>
			<th>LastName</th>
			<th>Email</th>
			<th>Gender</th>
			<th>Mobile</th>
			<th>Status</th>
			<th>Company</th>
			<th>CreatedAt</th>
			<th>UpdatedAt</th>
			<th>Edit</th>
			<th>Delete</th>
			<th>Address</th>
			<th>price</th>
			 
		</tr>
		  	<?php foreach ($result as $salesman):  ?>
		<tr>
			<td><?php  echo $salesman->salesman_id;?> </td>
			<td><?php echo $salesman->fname;?></td>
			<td><?php echo $salesman->lname;?></td>
			<td><?php echo $salesman->email;?></td>
			<td><?php echo $salesman->gender;?></td>
			<td><?php echo $salesman->mobile;?></td>
			<td><?php echo $salesman->status;?></td>
			<td><?php echo $salesman->company;?></td>
			<td><?php echo $salesman->create_at;?></td>
			<td><?php echo $salesman->update_at;?></td>
			<td><a href="<?php echo $this->getUrl()->getUrl('salesman','edit',['salesman_id'=>$salesman->salesman_id]);?>">Edit</a></td>
			<td><a href="<?php echo $this->getUrl()->getUrl('salesman','delete',['salesman_id'=>$salesman->salesman_id]);?>">Delete</a></td>
			<td><a href="<?php echo $this->getUrl()->getUrl('salesman_address','grid',['salesman_id'=>$salesman->salesman_id]);?>">Address</a></td>
			<td><a href="<?php echo $this->getUrl()->getUrl('salesman_price','grid',['salesman_id'=>$salesman->salesman_id]);?>">price</a></td> 
			
			
		</tr>
	<?php endforeach; ?>

	</table>

</body>
</html>